// ── FASTA — js/data.js ──
// All constant data: phases, benefits, presets, meals, workouts, learn cards

// Texts in PH, BENEFITS and PRESETS come verbatim from docs/kunskap/fastefaser.md (IDs fas.*, fordel.*, schema.*).
export const PH = [
  {h:0, l:"Matsmältning", i:"🍽️", c:"#f97316", d:"Kroppen bryter ner maten och tar upp näring. Blodsockret är förhöjt och kroppen lagrar överskott.", x:"Blodsockret stiger → kroppen frisätter insulin (ett hormon som hjälper cellerna att ta upp socker) → socker lagras som glykogen (kroppens korttidslager av socker) i levern och musklerna. Fett från maten lagras i fettvävnaden."},
  {h:4, l:"Tidig fasta", i:"⏳", c:"#fb923c", d:"Det mesta av maten är nu uppsugen. Kroppen börjar använda sitt sockerlager (glykogen) som bränsle.", x:"Levern bryter ner sitt glykogenlager och skickar socker till blodet för att hålla energin stabil. Insulinnivån börjar sjunka. Kroppen förbereder sig för att byta bränsle från mat till egna lager."},
  {h:12, l:"Mer fett som bränsle", i:"🔥", c:"#ef4444", d:"Levern har använt en stor del av sitt sockerlager. Kroppen hämtar allt mer energi från fett, och små mängder ketoner börjar bildas.", x:"Kroppen frigör fett från fettcellerna (lipolys – kroppens sätt att plocka ut fett som bränsle). Levern gör om en del av fettet till ketoner, ett reservbränsle som hjärnan och musklerna kan använda. När omställningen sker varierar mycket, ofta någonstans mellan 12 och 36 timmar, beroende på vad du ätit och hur aktiv du varit. Timern visar en uppskattning, inte vad som faktiskt händer i just din kropp."},
  {h:16, l:"Lätt ketos", i:"⚡", c:"#a855f7", d:"Ketonerna i blodet ökar, men nivåerna är fortfarande låga. Kroppen använder allt mer fett som bränsle.", x:"Ketoner (kroppens reservbränsle av fett) börjar stiga i blodet, men den verkliga ketosen kommer först efter något eller några dygn. I djurstudier ökar cellernas städprocess (autofagi) vid fasta, där cellerna bryter ner och återvinner gamla delar. Hos människor är autofagi svår att mäta, och man vet ännu inte säkert när eller hur mycket den ökar."},
  {h:24, l:"Ett dygn", i:"♻️", c:"#06b6d4", d:"Ketonerna fortsätter att stiga och kroppen hämtar allt mer energi från fett. Hunger kommer ofta i vågor, och en del får huvudvärk.", x:"Efter ungefär ett dygn bildar levern tydligt mer ketoner, som hjärnan och musklerna kan använda. I små studier ökar tillväxthormonet under fastor på flera dygn, samtidigt som kroppen sänker tillväxtsignalen IGF-1 för att spara energi. Ämnet BDNF, som har med minne och inlärning att göra, har i studier på människor ibland ökat, ibland minskat och ibland inte förändrats. Drick vatten och avbryt fastan om du blir yr eller mår dåligt."},
  {h:36, l:"Ketos", i:"🧬", c:"#3b82f6", d:"Kroppen får nu en stor del av sin energi från fett och ketoner.", x:"Ketonerna fortsätter att stiga i flera dagar och når sin högsta nivå först efter en till två veckors fasta. Påståenden om att nya celler bildas eller att generna ställer om till \"reparationsläge\" vid den här tiden bygger främst på djurstudier. Vid längre fastor bryter kroppen också ner en del muskler, så en del av viktnedgången är inte fett."},
  {h:48, l:"Två dygn", i:"✨", c:"#10b981", d:"Fett och ketoner är nu kroppens huvudbränsle. Så långa fastor passar bara friska vuxna, och helst efter att du pratat med vården.", x:"Tillväxtsignalen IGF-1 sjunker, vilket är kroppens sätt att spara energi. I försök på möss har flera dygns fasta följt av vanlig mat satt igång nybildning av blodceller från stamceller, men det är inte visat hos friska människor. Under långa fastor kan salter som natrium sjunka i blodet. Vanliga besvär är huvudvärk, trötthet och sömnproblem."},
  {h:72, l:"Tre dygn", i:"💎", c:"#8b5cf6", d:"Kroppen har ställt om helt till fett och ketoner som bränsle. Fastor längre än så här bör bara göras under medicinsk övervakning.", x:"Efter tre dygn får kroppen den allra största delen av sin energi från fett, och hjärnan använder allt mer ketoner. Påståenden om en \"omstart\" av immunsystemet, nya mitokondrier (cellernas energifabriker) eller maximal stamcellsaktivitet är inte visade hos människor. En studie av fastor på omkring tio dygn såg dessutom att inflammationsmarkörer i blodet ökade. Vill du fasta längre än tre dygn, gör det bara med stöd från vården."},
];

export const BENEFITS = [
  {h:4, t:"Tidig fasta initierad", i:"⏳", c:"#fb923c", e:["Insulinnivån sjunker","Sockerlagren börjar tömmas","Kroppen förbereder fettförbränning"]},
  {h:12, t:"Mer fett som bränsle", i:"🔥", c:"#ef4444", e:["Kroppen använder allt mer fett som bränsle","Små mängder ketoner börjar bildas","Insulinnivån är låg"]},
  {h:16, t:"Lätt ketos", i:"⚡", c:"#a855f7", e:["Ketonerna i blodet börjar öka","Cellernas städprocess (autofagi) kan öka – visat i djur, osäkert hos människor","Tankeförmågan påverkas oftast inte av kortare fastor, men en del blir trötta eller får huvudvärk"]},
  {h:24, t:"Ett dygn", i:"♻️", c:"#06b6d4", e:["Kroppen hämtar allt mer energi från fett","Ketonerna fortsätter att stiga","Tillväxthormonet ökar vid längre fastor"]},
  {h:36, t:"Ketos", i:"🧬", c:"#3b82f6", e:["Fett och ketoner är nu ett huvudbränsle","Ketonerna fortsätter att stiga i flera dagar"]},
  {h:48, t:"Två dygn", i:"✨", c:"#10b981", e:["Tillväxtsignalen IGF-1 sjunker för att spara energi","Kroppen har ställt om till fett och ketoner","Vanliga besvär: huvudvärk, trötthet, sömnproblem"]},
  {h:72, t:"Tre dygn", i:"💎", c:"#8b5cf6", e:["Kroppen har ställt om helt till fett och ketoner","Hjärnan använder allt mer ketoner","Längre fastor bör göras under medicinsk övervakning"]},
];

export const PRESETS = [
  {l:"∞", h:null, tag:"Löpande", p:"Ingen tidsgräns – fastan pågår tills du väljer att avsluta. Lyssna på kroppen och avbryt om du mår dåligt.", b:["Flexibelt","Inga tidskrav","Följ kroppen"]},
  {l:"16:8", h:16, tag:"Klassikern", p:"Den vanligaste formen av periodisk fasta och ett bra sätt att börja. De flesta sover en stor del av fastan. I studier ger den ungefär samma viktnedgång som att äta mindre på vanligt sätt. Ett tidigt ätfönster, till exempel 08–16, verkar vara något bättre för ämnesomsättningen än ett sent.", b:["Enkel att börja med","Kan göra det lättare att äta mindre","Vardagsvänlig"]},
  {l:"18:6", h:18, tag:"Lite längre", p:"Två timmar längre fasta än 16:8. Det finns inga säkra belägg för att det ger mer effekt, men det kan passa dig som vill ha ett kortare ätfönster.", b:["Kortare ätfönster","Lite längre tid med fett som bränsle","Ett steg upp från 16:8"]},
  {l:"20:4", h:20, tag:"Kort ätfönster", p:"Kallas ibland Warrior Diet. Med bara fyra timmar att äta på kan det vara svårt att få i sig tillräckligt med protein och näring.", b:["Längre tid med fett som bränsle","Kräver planering av måltiderna","Passar inte alla"]},
  {l:"OMAD", h:23, tag:"En måltid", p:"One Meal A Day – en måltid per dygn. Det är svårt att få i sig all näring på en måltid, och forskningen om hur det påverkar hälsan på lång sikt är begränsad.", b:["Förenklat ätande","Lång tid med fett som bränsle","Kräver en stor, näringsrik måltid"]},
  {l:"36h", h:36, tag:"Avancerad", p:"En och en halv dygns fasta. Kroppen hämtar en stor del av energin från fett och ketoner. Passar bara friska vuxna som provat kortare fastor.", b:["Ketos","Tillväxthormonet ökar","För dig med erfarenhet"]},
  {l:"48h", h:48, tag:"Utmanare", p:"Två dygns fasta. Kroppen har ställt om till fett och ketoner som huvudbränsle. Prata med vården först om du har en sjukdom eller tar mediciner.", b:["Djup ketos","Tillväxtsignalen IGF-1 sjunker","För dig med erfarenhet"]},
  {l:"72h", h:72, tag:"Tre dygn", p:"Tre dygns fasta. Påståenden om att immunsystemet \"startar om\" är inte visade hos människor. Så långa fastor bör bara göras med stöd från vården.", b:["Appens längsta schema","Kräver god hälsa och stöd från vården","Inte för nybörjare"]},
];

export const MEALS_PRE = [
  {l:"2 ägg",    k:140,pr:12,d:"2 kokta/stekta ägg"},
  {l:"3 ägg",    k:210,pr:18,d:"3 kokta/stekta ägg"},
  {l:"Ägg+ost",  k:260,pr:20,d:"2 ägg + 30g ost"},
  {l:"Kyckling", k:165,pr:31,d:"100g kycklingbröst"},
  {l:"Lax",      k:180,pr:25,d:"100g lax"},
  {l:"Eget",     k:null,pr:null,d:""},
];

export const WORKOUT_TYPES = [
  {l:"Promenad",     met:3.5, icon:"🚶"},
  {l:"Löpning",      met:9.0, icon:"🏃"},
  {l:"Cykling",      met:7.5, icon:"🚴"},
  {l:"Styrketräning",met:5.0, icon:"🏋️"},
  {l:"HIIT",         met:10.0,icon:"⚡"},
  {l:"Simning",      met:7.0, icon:"🏊"},
  {l:"Yoga/Stretch", met:2.5, icon:"🧘"},
  {l:"Eget...",      met:null,icon:"🏅"},
];

export const LC = [
  {id:1, cat:"Grunder",         i:"🌱",c:"#c8a84e",f:"Vad är periodisk fasta?",      fb:"Inte en diet — ett ätmönster. Du bestämmer när du äter, inte vad.",bk:"Periodisk fasta innebär att du cyklar mellan perioder av fasta och ätande. Du behöver inte räkna kalorier eller undvika specifika livsmedel. Forskning (Longo & Mattson, 2014) visar att fasteperioderna i sig ger starka hälsoeffekter — blodsockret stabiliseras, kroppen börjar bränna fett och startar sina egna reparationsprocesser.",src:"Longo & Mattson, Cell Metabolism 2014"},
  {id:2, cat:"Grunder",         i:"⚡",c:"#c8a84e",f:"Varför fungerar det?",          fb:"Nyckeln är insulin — det hormon som styr om kroppen lagrar eller bränner fett.",bk:"Insulin är ett hormon som frisätts när du äter, framför allt kolhydrater. Högt insulin = kroppen lagrar fett. Lågt insulin = kroppen kan frigöra och bränna fett. Under fasta sjunker insulinnivån med upp till 60% — kroppen låses upp och kan komma åt fettlagren som bränsle.",src:"Cahill GF Jr, Ann Rev Nutrition 2006"},
  {id:3, cat:"Grunder",         i:"🔄",c:"#c8a84e",f:"Vad händer timme för timme?",  fb:"Kroppen går igenom tydliga faser: matsmältning → sockerlager töms → fett bränns → fettbränsle → cellstädning.",bk:"0–4h: Insulin högt. 4–12h: Sockerlagren börjar tömmas. 12–16h: Fettförbränning ökar, fettbränsle (ketoner) produceras. 16–24h: Cellstädning aktiveras, tillväxthormon stiger. 24h+: Djup fettförbränning och cellförnyelse.",src:"Anton et al., Obesity Reviews 2018"},
  {id:4, cat:"Vetenskap",       i:"♻️",c:"#06b6d4",f:"Vad är autofagi (cellstädning)?",fb:"Kroppens inbyggda städ- och reparationssystem. Celler bryter ner och återvinner sina egna skadade delar.",bk:"Autofagi (från grekiskans 'självätande') är processen där celler identifierar och bryter ner skadade komponenter och återanvänder dem. Yoshinori Ohsumi fick Nobelpriset i medicin 2016 för att ha kartlagt hur autofagi fungerar. Kopplas till minskad risk för demens, cancer och åldrande.",src:"Ohsumi Y, Nobel Lecture 2016"},
  {id:5, cat:"Vetenskap",       i:"🧬",c:"#06b6d4",f:"När startar cellstädningen?",   fb:"Gradvis från ungefär 16 timmar, och är mest aktiv runt 24–48 timmar.",bk:"Cellstädningen ökar mätbart vid 24 timmars fasta. Den ökar gradvis — inte som en knapp. Att träna på fastande mage kan snabba på starten. Att äta protein eller kolhydrater stänger av cellstädningen via kroppens tillväxtsignal.",src:"Alirezaei et al., Autophagy 2010"},
  {id:6, cat:"Vetenskap",       i:"🧠",c:"#06b6d4",f:"Fasta och hjärnan",            fb:"Fettbränsle (ketoner) är ett renare bränsle för hjärnan. Många rapporterar skärpt fokus och klarhet.",bk:"Ketoner passerar lätt till hjärnan och ger energi med mindre biproduktsskador jämfört med socker. Dessutom ökar fasta ett ämne som stärker kopplingar mellan hjärnceller — kopplat till förbättrat minne, inlärning och skydd mot depression.",src:"Mattson MP, Nature Reviews Neuroscience 2019"},
  {id:7, cat:"Vetenskap",       i:"❤️",c:"#06b6d4",f:"Fasta och hjärtat",            fb:"Regelbunden fasta förbättrar blodtryck, kolesterol och kroppens förmåga att hantera socker.",bk:"En studie (Wilkinson et al., 2020) visade att 16:8-fasta sänkte det övre blodtrycket med ~7 mmHg och minskade mängden skadligt kolesterol med 12% under 12 veckor. Fetthalten i blodet minskade med 20%.",src:"Wilkinson et al., Cell Metabolism 2020"},
  {id:8, cat:"Träning",         i:"💪",c:"#f97316",f:"Tappar man muskler av att fasta?",fb:"Nej — kroppen skyddar aktivt muskelmassa under fasta genom att öka tillväxthormonet kraftigt.",bk:"Tillväxthormon kan stiga upp till 5 gånger normala nivåer vid 24 timmars fasta. Kroppen sparar muskelvävnad och bränner i stället fett. Styrketräning i fastat tillstånd ger likvärdig muskeluppbyggnad — förutsatt att du äter tillräckligt med protein efter.",src:"Ho et al., Journal of Clinical Investigation 1988"},
  {id:9, cat:"Träning",         i:"🏃",c:"#f97316",f:"Kan man träna under fasta?",   fb:"Ja — konditionsträning och lättare styrka fungerar utmärkt. Fettförbränningen är dessutom förhöjd.",bk:"Under fasta är kroppen redan i fettförbränningsläge, vilket gör att fettförbränningen under konditionsträning kan vara upp till 20% högre. För tung styrketräning rekommenderas att äta 1–2 timmar innan för bästa prestation.",src:"Schoenfeld & Aragon, Strength & Cond. Journal 2014"},
  {id:10,cat:"Träning",         i:"🥩",c:"#f97316",f:"När ska man äta efter träning?",fb:"Ät ett proteinrikt mål inom 1–2 timmar efter träning för att maximera muskelreparation.",bk:"Musklernas förmåga att ta upp protein och reparera sig är som störst direkt efter träning. Livsmedel rika på aminosyran leucin — som ägg, kyckling och vassleprotein — är mest effektiva.",src:"Morton et al., Am J Clinical Nutrition 2018"},
  {id:11,cat:"Vanliga farhågor",i:"🤒",c:"#ef4444",f:"Ska man fasta vid sjukdom?",   fb:"Vid feber eller allvarligare sjukdom — ät och drick normalt.",bk:"⚠️ Vid feber ökar kroppens energibehov med ungefär 10% per grad temperaturökning. Immunsystemet behöver socker och protein som bränsle. Fasta under pågående sjukdom kan förlänga återhämtningstiden.",src:"WHO 2020"},
  {id:12,cat:"Vanliga farhågor",i:"💊",c:"#ef4444",f:"Fasta och mediciner",          fb:"Många mediciner måste tas med mat för att fungera rätt. Rådgör alltid med din läkare.",bk:"⚠️ Insulin och blodsockersänkande mediciner kan ge farligt lågt blodsocker om du fastar. Blodtrycksmediciner och antiinflammatoriska smärtstillare behöver ofta tas med mat. Kontrollera alltid med läkare eller apotekare.",src:"Klinisk rekommendation"},
  {id:13,cat:"Vanliga farhågor",i:"🩸",c:"#ef4444",f:"Fasta vid diabetes",           fb:"Typ 2-diabetes kan förbättras märkbart. Typ 1-diabetes kräver alltid medicinsk övervakning.",bk:"⚠️ Periodisk fasta kan förbättra blodsockerkontroll vid typ 2-diabetes, men blodsockersänkande mediciner måste justeras av läkare. Personer med typ 1-diabetes bör ALDRIG fasta utan läkarövervakning.",src:"Sutton et al., Cell Metabolism 2018"},
  {id:14,cat:"Vanliga farhågor",i:"🤰",c:"#ef4444",f:"Graviditet & amning",          fb:"Rekommenderas inte — fostret och barnet behöver regelbunden tillförsel av näring.",bk:"⚠️ Under graviditet ökar energibehovet markant. Fasta kan påverka fostrets tillväxt negativt. Under amning kan ett energiunderskott minska mjölkproduktionen. Undvik fasta under dessa perioder.",src:"Academy of Nutrition and Dietetics 2021"},
  {id:15,cat:"Vanliga farhågor",i:"👴",c:"#ef4444",f:"Fasta och ålder (65+)",        fb:"Äldre bör vara försiktiga — risken för att förlora muskelmassa ökar med åldern.",bk:"⚠️ Från ca 30-årsåldern förlorar kroppen naturligt muskelmassa med åren. Fasta kan förstärka detta om man inte äter tillräckligt protein. Kortare fasteperioder (12–14 timmar) är ofta mer lämpliga än längre protokoll.",src:"Bauer et al., J Am Med Dir Assoc 2013"},
  {id:16,cat:"Vanliga farhågor",i:"😰",c:"#ef4444",f:"Ätstörningar & psykisk hälsa", fb:"Fasta kan trigga eller förvärra ätstörningar hos känsliga personer.",bk:"⚠️ Restriktiva ätmönster kan förstärka tvångsmässiga tankar kring mat och kropp. Vid depression eller ångest kan blodsockersvängningar förvärra humöret. Om du är osäker — konsultera en läkare eller psykolog.",src:"APA Clinical Recommendations 2022"},
  {id:17,cat:"Praktiskt",       i:"☕",c:"#8b5cf6",f:"Vad bryter fastan?",            fb:"Kalorier bryter fastan. Vatten, svart kaffe och osötat te håller dig i fastans tillstånd.",bk:"Det som avgör om fastan är bruten är framför allt insulinnivån. Kalorier höjer insulinet och avbryter de metabola fördelarna. Svart kaffe påverkar inte insulin märkbart.",src:"Maukonen et al., Nutrients 2020"},
  {id:18,cat:"Praktiskt",       i:"😣",c:"#8b5cf6",f:"Vanliga bieffekter",            fb:"Hunger, lätt yrsel och irritabilitet är vanligt de första 1–2 veckorna. Det går över.",bk:"De flesta bieffekter beror på brist på salter och mineraler (natrium, magnesium och kalium) som kroppen utsöndrar mer av i urinen under fasta. Lösning: drick saltat vatten eller buljong under längre fastor.",src:"Genoni et al., Nutrients 2019"},
  {id:19,cat:"Praktiskt",       i:"🌙",c:"#8b5cf6",f:"Bästa sättet att börja",        fb:"Börja försiktigt med 12 timmar och öka gradvis. Låt kroppen vänja sig i din takt.",bk:"Vecka 1: Sluta äta efter 20:00. Vecka 2: Skjut upp frukosten till 10:00. Vecka 3–4: Testa 16:8 konsekvent. De flesta märker tydliga fördelar efter 3–4 veckor när kroppen blivit van.",src:"Gabel et al., Nutrition and Healthy Aging 2018"},
];

export const ACTIVITY_LABELS = {
  stillasittande:"Stillasittande (kontorsarbete, lite rörelse)",
  lätt:"Lätt aktiv (promenader, lätt träning 1–2 ggr/v)",
  aktiv:"Regelbundet aktiv (träning 3–5 ggr/v)",
  atlet:"Atlet (intensiv träning 6–7 ggr/v)"
};

// Voluntary health questions (Profile page). Warning only, nothing is blocked.
// s = short warning, l = longer explanation, src = sources
// Texts come verbatim from docs/kunskap/halsa-och-sakerhet.md (IDs halsa.<k>).
export const HEALTH_FLAGS = [
  {k:"diabetesMeds", q:"Jag tar insulin, blodsockersänkande medicin eller en SGLT2-hämmare", s:"Fasta kan ge för lågt blodsocker eller en farlig syraförgiftning när du tar sådan medicin. Prata med din läkare eller diabetessköterska innan du fastar – behandlingen kan behöva anpassas.", l:"Insulin och vissa tabletter (till exempel sulfonylureider) sänker blodsockret även när du inte äter. Under en fasta kan blodsockret då bli för lågt, vilket kan ge skakighet, svettningar, förvirring och i värsta fall medvetslöshet. SGLT2-hämmare (till exempel Jardiance eller Forxiga) ges vid diabetes, hjärtsvikt och njursjukdom. Vid långa matuppehåll eller vätskebrist kan de ge en allvarlig syraförgiftning (ketoacidos), även när blodsockret ser normalt ut. Behandlingen kan behöva anpassas före och under fastan. Ändra aldrig medicineringen på egen hand, utan planera fastan tillsammans med vården.", src:"ADA 2026; EMA (Jardiance); IDF-DAR 2021/2026"},
  {k:"pregnant", q:"Jag är gravid eller ammar", s:"Under graviditet och amning ökar kroppens behov av energi och näring, och forskningen om fasta är begränsad. Prata med barnmorska, BVC eller läkare innan du fastar.", l:"När du är gravid eller ammar behöver du mer energi och näring än vanligt, särskilt sent i graviditeten och när du ammar. Det mesta vi vet om fasta under graviditet kommer från studier av ramadanfasta. De visar oftast ingen skillnad i födelsevikt, men stora studier har sett samband med vissa sämre utfall senare i barnets liv, särskilt när fastan skett tidigt i graviditeten. Forskningen är osäker och gäller inte fastor på flera dygn. Prata därför med din barnmorska, BVC eller läkare innan du provar fasta.", src:"Pradella m.fl. 2024; Al-Taiar m.fl. 2025; Livsmedelsverket"},
  {k:"eatingDisorder", q:"Jag har eller har haft en ätstörning", s:"Om du har eller har haft en ätstörning, prata med vården innan du börjar fasta. Följ i första hand den måltidsplan du fått i behandlingen.", l:"Regelbundna måltider är en viktig del av behandlingen vid flera ätstörningar, och att hoppa över måltider eller äta för lite kan göra besvären värre. Enkätstudier har sett ett samband mellan periodisk fasta och fler ätstörningssymtom, särskilt hos unga, men de kan inte visa vad som är orsak och verkan. Kontrollerade studier har oftast inte sett någon sådan ökning, men nästan inga har gjorts på personer som har eller har haft en ätstörning. Prata därför med din behandlare eller vårdcentral innan du ändrar när du äter. Stöd finns hos 1177 och Frisk & Fri.", src:"NICE NG69; Vizthum m.fl. 2023; Ganson m.fl. 2022"},
  {k:"under18", q:"Jag är under 18 år", s:"Kroppen växer fortfarande och behöver jämn tillgång till energi. Fasta rekommenderas inte för barn och unga utan stöd från vården.", l:"Under uppväxten och puberteten behöver kroppen ungefär lika mycket näring som en vuxen för att växa och utvecklas. Livsmedelsverket råder barn och unga att fördela maten på flera måltider under dagen. Forskningen om periodisk fasta hos barn och unga är begränsad, och hos unga har fasta kopplats till ätstörningsbeteenden. Ät hellre regelbundet, och prata med skolsköterskan eller vården om du har frågor om mat och vikt.", src:"Livsmedelsverket; Ganson m.fl. 2022"},
];

// halsa.friskrivning
export const HEALTH_DISCLAIMER = "FASTA ger allmän information och ersätter inte råd från vården. Mår du dåligt under en fasta, till exempel blir yr eller förvirrad, avbryt fastan och kontakta vården vid behov – ring 1177 för rådgivning eller 112 vid akuta besvär.";
