// ── FASTA — js/data.js ──
// All constant data: phases, benefits, presets, meals, workouts, learn cards

// Texts in PH, BENEFITS and PRESETS come verbatim from docs/kunskap/fastefaser.md (IDs fas.*, fordel.*, schema.*).
export const PH = [
  {h:0, l:"Matsmältning", i:"🍽️", c:"#f97316", d:"Kroppen bryter ner maten och tar upp näring. Blodsockret är förhöjt och kroppen lagrar överskott.", x:"Blodsockret stiger → kroppen frisätter insulin (ett hormon som hjälper cellerna att ta upp socker) → socker lagras som glykogen (kroppens korttidslager av socker) i levern och musklerna. Fett från maten lagras i fettvävnaden."},
  {h:4, l:"Tidig fasta", i:"⏳", c:"#fb923c", d:"Det mesta av maten är nu uppsugen. Kroppen börjar använda sitt sockerlager (glykogen) som bränsle.", x:"Levern bryter ner sitt glykogenlager och skickar socker till blodet för att hålla energin stabil. Insulinnivån börjar sjunka. Kroppen förbereder sig för att byta bränsle från mat till egna lager."},
  {h:12, l:"Mer fett som bränsle", i:"🔥", c:"#ef4444", d:"Levern har använt en stor del av sitt sockerlager. Kroppen hämtar allt mer energi från fett, och små mängder ketoner börjar bildas.", x:"Kroppen frigör fett från fettcellerna (lipolys – kroppens sätt att plocka ut fett som bränsle). Levern gör om en del av fettet till ketoner, ett reservbränsle som hjärnan och musklerna kan använda. När omställningen sker varierar mycket, ofta någonstans mellan 12 och 36 timmar, beroende på vad du ätit och hur aktiv du varit. Timern visar en uppskattning, inte vad som faktiskt händer i just din kropp."},
  {h:16, l:"Lätt ketos", i:"⚡", c:"#a855f7", d:"Ketonerna i blodet ökar, men nivåerna är fortfarande låga. Kroppen använder allt mer fett som bränsle.", x:"Ketoner (kroppens reservbränsle av fett) börjar stiga i blodet, men den verkliga ketosen kommer först efter något eller några dygn. I djurstudier ökar cellernas städprocess (autofagi) vid fasta, där cellerna bryter ner och återvinner gamla delar. Hos människor är autofagi svår att mäta, och man vet ännu inte säkert när eller hur mycket den ökar."},
  {h:24, l:"Ett dygn", i:"♻️", c:"#06b6d4", d:"Ketonerna fortsätter att stiga och kroppen hämtar allt mer energi från fett. Hunger kommer ofta i vågor, och en del får huvudvärk.", x:"Efter ungefär ett dygn bildar levern tydligt mer ketoner, som hjärnan och musklerna kan använda. I små studier ökar tillväxthormonet under fastor på flera dygn, samtidigt som kroppen sänker tillväxtsignalen IGF-1 för att spara energi. Ämnet BDNF, som har med minne och inlärning att göra, har i studier på människor ibland ökat, ibland minskat och ibland inte förändrats. Drick vatten och avbryt fastan om du blir yr eller mår dåligt."},
  {h:36, l:"Ketos", i:"🧬", c:"#3b82f6", d:"Kroppen får nu en stor del av sin energi från fett och ketoner.", x:"Ketonerna fortsätter att stiga i flera dagar och når sin högsta nivå först efter en till två veckors fasta. Påståenden om att nya celler bildas eller att generna ställer om till \"reparationsläge\" vid den här tiden bygger främst på djurstudier. Vid längre fastor bryter kroppen också ner en del muskler, så en del av viktnedgången är inte fett."},
  {h:48, l:"Två dygn", i:"✨", c:"#10b981", d:"Fett och ketoner är nu kroppens huvudbränsle. Så långa fastor passar bara friska vuxna, och helst efter att du pratat med vården.", x:"Tillväxtsignalen IGF-1 sjunker, vilket är kroppens sätt att spara energi. I försök på möss har flera dygns fasta följt av vanlig mat satt igång nybildning av blodceller från stamceller, men det är inte visat hos friska människor. Under långa fastor kan salter som natrium sjunka i blodet. Vanliga besvär är huvudvärk, trötthet och sömnproblem."},
  {h:72, l:"Tre dygn", i:"💎", c:"#8b5cf6", d:"Kroppen har ställt om helt till fett och ketoner som bränsle. Fastor längre än så här bör bara göras under medicinsk övervakning.", x:"Efter tre dygn får kroppen den allra största delen av sin energi från fett, och hjärnan använder allt mer ketoner. Påståenden om en \"omstart\" av immunsystemet, nya mitokondrier (cellernas energifabriker) eller maximal stamcellsaktivitet är inte visade hos människor. En studie av fastor på omkring tio dygn såg dessutom att inflammationsmarkörer i blodet ökade. Vill du fasta längre än tre dygn, gör det bara med stöd från vården."},
];

export const BENEFITS = [
  {h:4, t:"Tidig fasta initierad", i:"⏳", c:"#fb923c", e:["Insulinnivån sjunker","Sockerlagren börjar tömmas","Kroppen förbereder fettförbränning"]},
  {h:12, t:"Mer fett som bränsle", i:"🔥", c:"#ef4444", e:["Kroppen använder allt mer fett som bränsle","Små mängder ketoner börjar bildas","Insulinnivån är låg"]},
  {h:16, t:"Lätt ketos", i:"⚡", c:"#a855f7", e:["Ketonerna i blodet börjar öka","Cellernas städprocess (autofagi) kan öka – visat i djur, osäkert hos människor","Tankeförmågan påverkas oftast inte av kortare fastor, men en del blir trötta eller får huvudvärk"]},
  {h:24, t:"Ett dygn", i:"♻️", c:"#06b6d4", e:["Kroppen hämtar allt mer energi från fett","Ketonerna fortsätter att stiga","Tillväxthormonet ökar vid längre fastor"]},
  {h:36, t:"Ketos", i:"🧬", c:"#3b82f6", e:["Fett och ketoner är nu ett huvudbränsle","Ketonerna fortsätter att stiga i flera dagar"]},
  {h:48, t:"Två dygn", i:"✨", c:"#10b981", e:["Tillväxtsignalen IGF-1 sjunker för att spara energi","Kroppen har ställt om till fett och ketoner","Vanliga besvär: huvudvärk, trötthet, sömnproblem"]},
  {h:72, t:"Tre dygn", i:"💎", c:"#8b5cf6", e:["Kroppen har ställt om helt till fett och ketoner","Hjärnan använder allt mer ketoner","Längre fastor bör göras under medicinsk övervakning"]},
];

export const PRESETS = [
  {l:"∞", h:null, tag:"Löpande", p:"Ingen tidsgräns – fastan pågår tills du väljer att avsluta. Lyssna på kroppen och avbryt om du mår dåligt.", b:["Flexibelt","Inga tidskrav","Följ kroppen"]},
  {l:"16:8", h:16, tag:"Klassikern", p:"Den vanligaste formen av periodisk fasta och ett bra sätt att börja. De flesta sover en stor del av fastan. I studier ger den ungefär samma viktnedgång som att äta mindre på vanligt sätt. Ett tidigt ätfönster, till exempel 08–16, verkar vara något bättre för ämnesomsättningen än ett sent.", b:["Enkel att börja med","Kan göra det lättare att äta mindre","Vardagsvänlig"]},
  {l:"18:6", h:18, tag:"Lite längre", p:"Två timmar längre fasta än 16:8. Det finns inga säkra belägg för att det ger mer effekt, men det kan passa dig som vill ha ett kortare ätfönster.", b:["Kortare ätfönster","Lite längre tid med fett som bränsle","Ett steg upp från 16:8"]},
  {l:"20:4", h:20, tag:"Kort ätfönster", p:"Kallas ibland Warrior Diet. Med bara fyra timmar att äta på kan det vara svårt att få i sig tillräckligt med protein och näring.", b:["Längre tid med fett som bränsle","Kräver planering av måltiderna","Passar inte alla"]},
  {l:"OMAD", h:23, tag:"En måltid", p:"One Meal A Day – en måltid per dygn. Det är svårt att få i sig all näring på en måltid, och forskningen om hur det påverkar hälsan på lång sikt är begränsad.", b:["Förenklat ätande","Lång tid med fett som bränsle","Kräver en stor, näringsrik måltid"]},
  {l:"36h", h:36, tag:"Avancerad", p:"En och en halv dygns fasta. Kroppen hämtar en stor del av energin från fett och ketoner. Passar bara friska vuxna som provat kortare fastor.", b:["Ketos","Tillväxthormonet ökar","För dig med erfarenhet"]},
  {l:"48h", h:48, tag:"Utmanare", p:"Två dygns fasta. Kroppen har ställt om till fett och ketoner som huvudbränsle. Prata med vården först om du har en sjukdom eller tar mediciner.", b:["Djup ketos","Tillväxtsignalen IGF-1 sjunker","För dig med erfarenhet"]},
  {l:"72h", h:72, tag:"Tre dygn", p:"Tre dygns fasta. Påståenden om att immunsystemet \"startar om\" är inte visade hos människor. Så långa fastor bör bara göras med stöd från vården.", b:["Appens längsta schema","Kräver god hälsa och stöd från vården","Inte för nybörjare"]},
];

export const MEALS_PRE = [
  {l:"2 ägg",    k:140,pr:12,d:"2 kokta/stekta ägg"},
  {l:"3 ägg",    k:210,pr:18,d:"3 kokta/stekta ägg"},
  {l:"Ägg+ost",  k:260,pr:20,d:"2 ägg + 30g ost"},
  {l:"Kyckling", k:165,pr:31,d:"100g kycklingbröst"},
  {l:"Lax",      k:180,pr:25,d:"100g lax"},
  {l:"Eget",     k:null,pr:null,d:""},
];

export const WORKOUT_TYPES = [
  {l:"Promenad",      icon:"🚶"},
  {l:"Löpning",       icon:"🏃"},
  {l:"Cykling",       icon:"🚴"},
  {l:"Styrketräning", icon:"🏋️"},
  {l:"HIIT",          icon:"⚡"},
  {l:"Simning",       icon:"🏊"},
  {l:"Yoga/Stretch",  icon:"🧘"},
  {l:"Eget...",       icon:"🏅", custom:true},
];

export const LC = [
  {id:1, cat:"Grunder",         i:"🌱",c:"#c8a84e",f:"Vad är periodisk fasta?",      fb:"Ett ätmönster, inte en diet. Du bestämmer när du äter – vad du äter spelar fortfarande roll.",bk:"Periodisk fasta innebär att du växlar mellan tider då du äter och tider då du inte äter. Stora sammanställningar av randomiserade studier visar att det ger ungefär samma viktnedgång och förbättringar av till exempel blodsocker och blodfetter som att äta mindre på vanligt sätt. För en del är fasta helt enkelt ett enklare sätt att äta mindre. Mycket av det man läser om cellreparation och längre liv bygger på djurstudier.",src:"Semnani-Azad m.fl., BMJ 2025; Garegnani m.fl., Cochrane 2026"},
  {id:2, cat:"Grunder",         i:"⚡",c:"#c8a84e",f:"Varför fungerar det?",          fb:"Insulin är ett hormon som styr om kroppen lagrar energi eller hämtar ur sina lager.",bk:"Insulin frisätts när du äter, framför allt kolhydrater, och hjälper kroppen att ta upp och lagra energi. När du inte äter sjunker insulinet, och det blir lättare för kroppen att frigöra fett och använda det som bränsle. Men om du går ner i vikt avgörs framför allt av hur mycket du äter totalt, inte bara av när.",src:"Cahill, Annu Rev Nutr 2006; Semnani-Azad m.fl., BMJ 2025"},
  {id:3, cat:"Grunder",         i:"🔄",c:"#c8a84e",f:"Vad händer timme för timme?",  fb:"Kroppen ställer gradvis om från socker i maten till sina lager och sedan allt mer till fett och ketoner. Tiderna varierar mellan personer.",bk:"Ungefärligt förlopp: 0–4 h tar kroppen upp näring från maten. Därefter hämtar den socker ur leverns lager. Någon gång mellan 12 och 36 timmar ökar fettförbränningen tydligt och små mängder ketoner bildas. Efter ett dygn stiger ketonerna mer, och de når sin högsta nivå först efter ungefär två veckor. Påståenden om cellstädning och cellförnyelse vid bestämda klockslag är inte visade hos människor.",src:"Anton m.fl., Obesity 2018; Cahill, Annu Rev Nutr 2006"},
  {id:4, cat:"Vetenskap",       i:"♻️",c:"#06b6d4",f:"Vad är autofagi (cellstädning)?",fb:"Kroppens inbyggda städ- och reparationssystem. Celler bryter ner och återvinner sina egna skadade delar.",bk:"Autofagi (från grekiskans \"självätande\") är processen där celler bryter ner skadade delar och återanvänder dem. Yoshinori Ohsumi fick Nobelpriset i fysiologi eller medicin 2016 för att ha kartlagt hur den fungerar. Kopplingar till demens, cancer och åldrande kommer främst från studier på celler och djur. Hos människor är autofagi svår att mäta, och det är inte visat att fasta påverkar sjukdomsrisk via den.",src:"Nobelförsamlingen 2016; Bensalem m.fl., J Physiol 2025"},
  {id:5, cat:"Vetenskap",       i:"🧬",c:"#06b6d4",f:"När startar cellstädningen?",   fb:"Det vet man inte säkert hos människor. Tidpunkterna som ofta nämns kommer från djurförsök.",bk:"Studien som ofta citeras (Alirezaei m.fl. 2010) visade kraftigt ökad autofagi i nervceller hos möss efter 24–48 timmars fasta. Möss har mycket snabbare ämnesomsättning än människor, så tiderna går inte att överföra. Hos människor är autofagi svår att mäta i vävnad, och man vet inte när den ökar eller hur mycket. Det finns alltså ingen belagd anledning att förlänga en fasta för att \"nå\" cellstädning.",src:"Alirezaei m.fl., Autophagy 2010 (möss); Bensalem m.fl., J Physiol 2025"},
  {id:6, cat:"Vetenskap",       i:"🧠",c:"#06b6d4",f:"Fasta och hjärnan",            fb:"Hjärnan kan använda ketoner som bränsle under fasta. Hos friska vuxna påverkas tankeförmågan i genomsnitt inte av kortare fastor.",bk:"Under längre fasta får hjärnan en allt större del av sin energi från ketoner. I djurstudier har fasta ökat ämnet BDNF, som har med minne och inlärning att göra. Hos människor är resultaten spretiga: BDNF har ökat i vissa studier och minskat i andra. En stor sammanställning från 2025 fann ingen genomsnittlig skillnad i tankeförmåga efter kortare fastor, varken bättre eller sämre.",src:"Bamberg & Moreau, Psychol Bull 2025; Alkurd m.fl., Medicina 2024; Mattson m.fl., Nat Rev Neurosci 2018"},
  {id:7, cat:"Vetenskap",       i:"❤️",c:"#06b6d4",f:"Fasta och hjärtat",            fb:"Blodtryck, blodfetter och blodsocker förbättras ofta – men ungefär lika mycket som när man går ner i vikt på andra sätt.",bk:"Den ofta citerade studien (Wilkinson m.fl. 2020) följde 19 personer med metabolt syndrom som åt inom 10 timmar per dag i 12 veckor, utan jämförelsegrupp. Större sammanställningar av randomiserade studier visar att fasta förbättrar blodtryck, blodfetter och blodsocker ungefär lika mycket som vanlig kalorirestriktion. Förbättringarna hänger alltså främst ihop med viktnedgången, inte med fastan i sig.",src:"Semnani-Azad m.fl., BMJ 2025; Schroor m.fl., Adv Nutr 2024"},
  {id:8, cat:"Träning",         i:"💪",c:"#f97316",f:"Tappar man muskler av att fasta?",fb:"En del av viktnedgången är muskler, precis som vid andra dieter. Styrketräning och tillräckligt med protein hjälper dig att behålla dem.",bk:"Vid periodisk fasta förloras ungefär lika mycket muskler och annan fettfri vävnad som vid vanlig kalorirestriktion, eller något mer. Vid flerdygnsfastor är andelen större: i studier av 5–20 dygns fasta var ungefär två tredjedelar av viktnedgången fettfri massa. Påståendet att tillväxthormonet ökar \"5 gånger\" och skyddar musklerna bygger på mycket små studier. Det som faktiskt hjälper är styrketräning och tillräckligt med protein över dagen.",src:"Schroor m.fl., Adv Nutr 2024; Ezpeleta m.fl., Nutr Rev 2024; Morton m.fl., Br J Sports Med 2018"},
  {id:9, cat:"Träning",         i:"🏃",c:"#f97316",f:"Kan man träna under fasta?",   fb:"Ja, för de flesta friska. Kroppen använder mer fett under passet, men långa konditionspass går oftast bättre om du har ätit.",bk:"När du tränar på fastande mage använder kroppen mer fett som bränsle under själva passet. Det betyder inte att du förlorar mer fett över tid – det avgörs av det totala energiintaget. Pass kortare än ungefär en timme påverkas i regel inte. Vid konditionspass längre än en timme presterar de flesta bättre om de har ätit före. Blir du yr eller svag, avbryt och ät.",src:"Aird m.fl., Scand J Med Sci Sports 2018; Vieira m.fl., Br J Nutr 2016"},
  {id:10,cat:"Träning",         i:"🥩",c:"#f97316",f:"När ska man äta efter träning?",fb:"Det viktigaste är att få i dig tillräckligt med protein över hela dagen. Exakt när efter passet spelar mindre roll.",bk:"Den tidigare bilden av ett kort \"anabolt fönster\" direkt efter träning stöds inte av nyare forskning. När den totala mängden protein är densamma spelar det liten roll om du äter proteinet före eller efter passet. Vinsten av mer protein planar ut vid ungefär 1,6 gram per kilo kroppsvikt och dag. Med ett kort ätfönster kan det vara svårt att nå dit, så planera proteinrika måltider.",src:"Morton m.fl., Br J Sports Med 2018; Casuso & Goossens, Nutrients 2025"},
  {id:11,cat:"Vanliga farhågor",i:"🤒",c:"#ef4444",f:"Ska man fasta vid sjukdom?",   fb:"Nej. Vid feber eller annan sjukdom – ät och drick som vanligt.",bk:"Vid feber och infektion ökar kroppens energi- och vätskebehov. Att fasta samtidigt kan göra att du känner dig sämre och blir uttorkad. Ät och drick ordentligt tills du är frisk, och vänta med fasta tills du mår som vanligt igen.",src:"1177"},
  {id:12,cat:"Vanliga farhågor",i:"💊",c:"#ef4444",f:"Fasta och mediciner",          fb:"Vissa läkemedel ska tas med mat, och vissa kan ge för lågt blodsocker när du inte äter. Fråga läkare eller apotek innan du fastar.",bk:"Insulin och vissa diabetesläkemedel kan ge för lågt blodsocker under fasta. SGLT2-hämmare (till exempel Jardiance eller Forxiga), som också ges vid hjärtsvikt och njursjukdom, kan vid långa matuppehåll ge en allvarlig syraförgiftning. Andra läkemedel ska tas med mat för att inte ge magbesvär. Ändra aldrig din medicinering på egen hand – fråga läkare eller apotek vad som gäller för just dina läkemedel.",src:"ADA 2026; EMA (Jardiance)"},
  {id:13,cat:"Vanliga farhågor",i:"🩸",c:"#ef4444",f:"Fasta vid diabetes",           fb:"Vid typ 2-diabetes kan fasta förbättra blodsockret så länge man fortsätter, men medicinerna behöver ofta anpassas. Vid typ 1-diabetes krävs alltid plan med vården.",bk:"Randomiserade studier visar att periodisk fasta kan sänka långtidsblodsockret (HbA1c) och vikten vid typ 2-diabetes på kort sikt, ungefär som annan viktnedgång. Effekten försvinner när man slutar. Insulin och vissa tabletter kan ge för lågt blodsocker under fasta, så behandlingen måste planeras med vården. Vid typ 1-diabetes är risken för både lågt blodsocker och syraförgiftning större, och fasta bör bara göras med en plan från vården.",src:"Liu m.fl., Nutr Res 2025; ADA 2026; IDF-DAR 2021"},
  {id:14,cat:"Vanliga farhågor",i:"🤰",c:"#ef4444",f:"Graviditet & amning",          fb:"Forskningen räcker inte för att säga att fasta är säker under graviditet och amning. Prata med barnmorska, BVC eller läkare först.",bk:"Under graviditet och amning ökar kroppens behov av energi och näring. Studier av ramadanfasta visar oftast ingen skillnad i födelsevikt, men stora studier har sett samband med vissa sämre utfall senare i barnets liv, särskilt vid fasta tidigt i graviditeten. Forskningen är osäker och gäller inte fastor på flera dygn. Prata därför med barnmorska, BVC eller läkare innan du provar fasta.",src:"Pradella m.fl., Hum Reprod Update 2024; Al-Taiar m.fl., Int J Gynaecol Obstet 2025; Livsmedelsverket"},
  {id:15,cat:"Vanliga farhågor",i:"👴",c:"#ef4444",f:"Fasta och ålder (65+)",        fb:"Med stigande ålder blir det svårare att behålla muskler. Fasta som gör att du äter mindre protein kan förstärka det.",bk:"Muskelmassan minskar gradvis med åldern. Äldre behöver därför ofta mer protein än yngre, ungefär 1,0–1,2 gram per kilo kroppsvikt och dag enligt expertrekommendationer. Europeiska riktlinjer för äldre avråder generellt från bantning och strikta kostupplägg om man inte har en tydlig medicinsk anledning. Har du tappat vikt eller aptit, eller känner dig svagare, prata med vården innan du fastar.",src:"Bauer m.fl., JAMDA 2013; Volkert m.fl. (ESPEN), Clin Nutr 2022"},
  {id:16,cat:"Vanliga farhågor",i:"😰",c:"#ef4444",f:"Ätstörningar & psykisk hälsa", fb:"Har du eller har du haft en ätstörning, prata med vården innan du börjar fasta.",bk:"Regelbundna måltider är en viktig del av behandlingen vid flera ätstörningar, och att hoppa över måltider eller äta för lite kan göra besvären värre. Enkätstudier har sett samband mellan periodisk fasta och fler ätstörningssymtom, särskilt hos unga, men de visar inte orsak och verkan. Om fasta gör att du tänker mycket på mat, vikt eller kropp – ta det som en signal att prata med någon. Stöd finns hos 1177 och Frisk & Fri.",src:"NICE NG69; Vizthum m.fl., Appetite 2023; Ganson m.fl., Eating Behaviors 2022"},
  {id:17,cat:"Praktiskt",       i:"☕",c:"#8b5cf6",f:"Vad bryter fastan?",            fb:"Mat och dryck med kalorier bryter fastan. Vatten, kaffe och te utan socker eller mjölk innehåller nästan inga kalorier.",bk:"Allt som innehåller energi – mat, mjölk i kaffet, juice, läsk med socker – avbryter fastan. Vatten, svart kaffe och osötat te innehåller nästan ingen energi och brukar räknas som tillåtna. Det finns lite forskning om exakt hur kaffe påverkar kroppen under fasta, så det är osäkert om det spelar roll för något annat än kalorierna.",src:"– (praktisk information)"},
  {id:18,cat:"Praktiskt",       i:"😣",c:"#8b5cf6",f:"Vanliga bieffekter",            fb:"Hunger, huvudvärk och trötthet är vanligt i början, särskilt vid längre fastor. I studier av kortare fasteupplägg är besvären ofta lindriga.",bk:"En sammanställning av 15 randomiserade studier fann inte fler fall av huvudvärk eller trötthet hos dem som fastade jämfört med dem som inte gjorde det. Vid flerdygnsfastor är huvudvärk, sömnproblem, hunger och trötthet vanligt, och salter som natrium kan sjunka i blodet. Drick vatten. Blir du yr, förvirrad eller får hjärtklappning – avbryt fastan och ät.",src:"Zhong m.fl., Nutr J 2024; Ezpeleta m.fl., Nutr Rev 2024"},
  {id:19,cat:"Praktiskt",       i:"🌙",c:"#8b5cf6",f:"Bästa sättet att börja",        fb:"Börja försiktigt med 12 timmar och öka gradvis. Låt kroppen vänja sig i din takt.",bk:"Ett exempel: vecka 1, sluta äta efter kl. 20. Vecka 2, skjut upp frukosten till kl. 10. Vecka 3–4, prova 16:8 om det känns bra. Ett tidigt ätfönster, till exempel 08–16, verkar vara något bättre för ämnesomsättningen än ett sent. Det viktigaste är ett upplägg du kan hålla, och att du fortfarande äter tillräckligt och varierat.",src:"Chen m.fl., BMJ Medicine 2026"},
];

export const ACTIVITY_LABELS = {
  stillasittande:"Stillasittande (kontorsarbete, lite rörelse)",
  lätt:"Lätt aktiv (promenader, lätt träning 1–2 ggr/v)",
  aktiv:"Regelbundet aktiv (träning 3–5 ggr/v)",
  atlet:"Atlet (intensiv träning 6–7 ggr/v)"
};

// Voluntary health questions (Profile page). Warning only, nothing is blocked.
// s = short warning, l = longer explanation, src = sources
// Texts come verbatim from docs/kunskap/halsa-och-sakerhet.md (IDs halsa.<k>).
export const HEALTH_FLAGS = [
  {k:"diabetesMeds", q:"Jag tar insulin, blodsockersänkande medicin eller en SGLT2-hämmare", s:"Fasta kan ge för lågt blodsocker eller en farlig syraförgiftning när du tar sådan medicin. Prata med din läkare eller diabetessköterska innan du fastar – behandlingen kan behöva anpassas.", l:"Insulin och vissa tabletter (till exempel sulfonylureider) sänker blodsockret även när du inte äter. Under en fasta kan blodsockret då bli för lågt, vilket kan ge skakighet, svettningar, förvirring och i värsta fall medvetslöshet. SGLT2-hämmare (till exempel Jardiance eller Forxiga) ges vid diabetes, hjärtsvikt och njursjukdom. Vid långa matuppehåll eller vätskebrist kan de ge en allvarlig syraförgiftning (ketoacidos), även när blodsockret ser normalt ut. Behandlingen kan behöva anpassas före och under fastan. Ändra aldrig medicineringen på egen hand, utan planera fastan tillsammans med vården.", src:"ADA 2026; EMA (Jardiance); IDF-DAR 2021/2026"},
  {k:"pregnant", q:"Jag är gravid eller ammar", s:"Under graviditet och amning ökar kroppens behov av energi och näring, och forskningen om fasta är begränsad. Prata med barnmorska, BVC eller läkare innan du fastar.", l:"När du är gravid eller ammar behöver du mer energi och näring än vanligt, särskilt sent i graviditeten och när du ammar. Det mesta vi vet om fasta under graviditet kommer från studier av ramadanfasta. De visar oftast ingen skillnad i födelsevikt, men stora studier har sett samband med vissa sämre utfall senare i barnets liv, särskilt när fastan skett tidigt i graviditeten. Forskningen är osäker och gäller inte fastor på flera dygn. Prata därför med din barnmorska, BVC eller läkare innan du provar fasta.", src:"Pradella m.fl. 2024; Al-Taiar m.fl. 2025; Livsmedelsverket"},
  {k:"eatingDisorder", q:"Jag har eller har haft en ätstörning", s:"Om du har eller har haft en ätstörning, prata med vården innan du börjar fasta. Följ i första hand den måltidsplan du fått i behandlingen.", l:"Regelbundna måltider är en viktig del av behandlingen vid flera ätstörningar, och att hoppa över måltider eller äta för lite kan göra besvären värre. Enkätstudier har sett ett samband mellan periodisk fasta och fler ätstörningssymtom, särskilt hos unga, men de kan inte visa vad som är orsak och verkan. Kontrollerade studier har oftast inte sett någon sådan ökning, men nästan inga har gjorts på personer som har eller har haft en ätstörning. Prata därför med din behandlare eller vårdcentral innan du ändrar när du äter. Stöd finns hos 1177 och Frisk & Fri.", src:"NICE NG69; Vizthum m.fl. 2023; Ganson m.fl. 2022"},
  {k:"under18", q:"Jag är under 18 år", s:"Kroppen växer fortfarande och behöver jämn tillgång till energi. Fasta rekommenderas inte för barn och unga utan stöd från vården.", l:"Under uppväxten och puberteten behöver kroppen ungefär lika mycket näring som en vuxen för att växa och utvecklas. Livsmedelsverket råder barn och unga att fördela maten på flera måltider under dagen. Forskningen om periodisk fasta hos barn och unga är begränsad, och hos unga har fasta kopplats till ätstörningsbeteenden. Ät hellre regelbundet, och prata med skolsköterskan eller vården om du har frågor om mat och vikt.", src:"Livsmedelsverket; Ganson m.fl. 2022"},
];

// halsa.friskrivning
export const HEALTH_DISCLAIMER = "FASTA ger allmän information och ersätter inte råd från vården. Mår du dåligt under en fasta, till exempel blir yr eller förvirrad, avbryt fastan och kontakta vården vid behov – ring 1177 för rådgivning eller 112 vid akuta besvär.";

// Approved copy: docs/kunskap/fas1.md
export const GOALS = {
  "intro": "Sätt ett mål som du kan följa, till exempel hur många fastor du vill göra i veckan eller en målvikt. Målet är ditt eget, och du kan ändra det när du vill.",
  "vikt": "Ett rimligt första mål är ofta att gå ner 3–5 procent av din vikt. Vid övervikt kan redan det ge tydliga hälsovinster.",
  "viktHalsa": "Du har angett något i Hälsa och säkerhet som gör att ett viktmål kan vara olämpligt. Prata med vården innan du sätter ett mål för din vikt.",
  "source": "Wharton m.fl., CMAJ 2020"
};
export const PROGRAM_INTRO = "Ett program är en plan för några veckor där appen föreslår hur länge du fastar varje dag. Du kan pausa, byta eller avsluta när du vill, och du behöver inte ta igen missade dagar.";
export const PROGRAMS = {
  "komIgang": {
    "name": "Kom igång",
    "plan": "Vecka 1: 12 timmar · Vecka 2: 14 timmar · Vecka 3–4: 16 timmar",
    "description": "För dig som inte har fastat förut. Fastan ökar stegvis från 12 till 16 timmar under fyra veckor, så att du hinner känna efter hur kroppen reagerar. Det finns inga studier som visar att en viss upptrappning är bäst – det här är ett sätt att prova dig fram. Huvudvärk, trötthet och hunger är vanligt, men i studier har besvären oftast varit lindriga. Blir du yr eller mår dåligt, avbryt fastan.",
    "source": "Allaf m.fl., Cochrane 2021; Chen m.fl., Front Nutr 2025",
    "days": 28
  },
  "vana168": {
    "name": "16:8 som vana",
    "plan": "8 veckor · 16 timmars fasta minst 5 dagar i veckan",
    "description": "För dig som klarar 16:8 och vill göra det till en vana. Målet är 16 timmars fasta minst fem dagar i veckan i åtta veckor. I studier ger periodisk fasta ungefär samma viktnedgång som att äta mindre på vanligt sätt. Det viktigaste är därför att upplägget passar din vardag, så att du kan hålla fast vid det.",
    "source": "Semnani-Azad m.fl., BMJ 2025; Garegnani m.fl., Cochrane 2026",
    "days": 56
  },
  "tidigt": {
    "name": "Tidigt ätfönster",
    "plan": "8 veckor · ät inom 8 timmar, sista målet före kl. 17 · till exempel 08–16 eller 09–17",
    "description": "Du äter inom åtta timmar och tar dagens sista mål före klockan 17. En stor sammanställning av randomiserade studier fann att ett tidigt ätfönster gav lite större viktnedgång och bättre insulinvärden än ett sent, i genomsnitt drygt ett kilo. Det kan vara svårt att få ihop med jobb, träning och middag med familjen, så välj det bara om det passar din vardag.",
    "source": "Chen m.fl., BMJ Medicine 2026",
    "days": 56
  }
};
